/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClienteController;
import javax.swing.JOptionPane;
import model.Cliente;
import utils.Utils;

/**
 *
 * @author prisc
 */
public final class FrAltCliente extends javax.swing.JDialog {

    private int id;

    /**
     * Creates new form FrAltCadUsuario
     *
     * @param id
     */
    public void setId(int id) {
        this.id = id;
    }

    public FrAltCliente(java.awt.Frame parent, boolean modal, int id) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        setId(id);
        carregarCliente();

    }

    ClienteController controller = new ClienteController();
    Cliente cl = new Cliente();

    public void gravarCliente() {
        ClienteController controller = new ClienteController();
        Cliente cliente = new Cliente();

        // Preenche os dados do cliente capturados do formulário
        cliente.setId(this.id); // <- IMPORTANTE: definir o id para que seja atualizado
        cliente.setNome(txtNome.getText().trim());
        cliente.setEmail(txtEmail.getText().trim()); // <- Corrigido aqui
        cliente.setTelefone(txtTelefone.getText().trim());
        cliente.setCpf(txtCpf.getText().trim());// <- Adicionado caso exista campo telefone no modelo
        cliente.setDataNascimento(Utils.converterStringToDate(txtDataNasc.getText().trim()));

        // Atualiza o cliente no banco de dados
        cliente.setId(id);  // Adiciona o ID ao cliente
        cliente.setNome(txtNome.getText().trim());  // Captura o nome do cliente
        cliente.setEmail(txtEmail.getText().trim()); // Captura o email
        cliente.setTelefone(txtTelefone.getText().trim()); 
        cliente.setCpf(txtCpf.getText().trim());// Captura o telefone
        cliente.setDataNascimento(Utils.converterStringToDate(txtDataNasc.getText().trim()));  // Captura e converte a data de nascimento

        // Chama o método do controlador para atualizar o cliente
        if (controller.atualizar(cliente)) {
            JOptionPane.showMessageDialog(null, "Cliente atualizado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(null, "Erro: Cliente não pôde ser atualizado.");
        }
    }

    public void carregarCliente() {
        // Busca os dados do cliente no banco de dados, utilizando o controlador
        ClienteController controller = new ClienteController();
        Cliente cliente = controller.buscarPorId(id); // Busca o cliente pelo ID

        // Preenche os campos do formulário com os dados do cliente
        String codigo = String.valueOf(cliente.getId()); // Converte o ID para String
        txtCod.setText(codigo); // Campo para o código/ID
        txtNome.setText(cliente.getNome()); // Nome do cliente
        txtEmail.setText((cliente.getEmail()));
        txtTelefone.setText(cliente.getTelefone()); // Telefone do cliente
        txtEmail.setText(cliente.getEmail()); // ✅
        txtTelefone.setText(cliente.getTelefone()); // ✅
        txtDataNasc.setText(Utils.converterDateToString(cliente.getDataNascimento())); // Converte a data de nascimento para String

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblDataNasc = new javax.swing.JLabel();
        txtDataNasc = new javax.swing.JFormattedTextField();
        txtTelefone = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        btnVoltar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        lblCpf = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(204, 204, 0));
        lblTitulo.setText("Alteração nos dados do Cliente");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        lblNome.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblNome.setForeground(new java.awt.Color(204, 204, 0));
        lblNome.setText("Nome");
        jPanel1.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        lblEmail.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(204, 204, 0));
        lblEmail.setText("E-mail");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        lblDataNasc.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblDataNasc.setForeground(new java.awt.Color(204, 204, 0));
        lblDataNasc.setText("Data de Nascimento");
        jPanel1.add(lblDataNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        txtDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jPanel1.add(txtDataNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 130, -1));
        jPanel1.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 181, -1));

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 181, -1));

        btnVoltar.setBackground(new java.awt.Color(255, 255, 153));
        btnVoltar.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/voltar.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoltarMouseClicked(evt);
            }
        });
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 110, 30));

        btnSalvar.setBackground(new java.awt.Color(255, 255, 153));
        btnSalvar.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        jPanel1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, -1, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 0));
        jLabel1.setText("Código");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        txtCod.setEditable(false);
        jPanel1.add(txtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 43, -1));

        lblTelefone.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblTelefone.setForeground(new java.awt.Color(204, 204, 0));
        lblTelefone.setText("Telefone");
        jPanel1.add(lblTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 181, -1));
        jPanel1.add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 181, -1));

        lblCpf.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblCpf.setForeground(new java.awt.Color(204, 204, 0));
        lblCpf.setText("Cpf");
        jPanel1.add(lblCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
        if (verificarCampos()) {
            gravarCliente();
        }
    }//GEN-LAST:event_btnSalvarMouseClicked

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed
    private void btnVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnVoltarMouseClicked

    public boolean verificarCampos() {

        String nome = txtNome.getText().trim();
        String email = txtEmail.getText().trim();
        String telefone = txtTelefone.getText().trim();
        String cpf = txtCpf.getText().trim();
        String dataNascimento = txtDataNasc.getText().trim();

        if (txtNome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo 'Nome' está em branco");
            return false;
        }
        if (!nome.matches("^[A-Za-zÀ-ÖØ-öø-ÿ ]+$")) {
            JOptionPane.showMessageDialog(null, "Nome inválido! Use apenas letras e espaços.");
            return false;
        }

        if (txtEmail.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo 'Email' está em branco");
            return false;
        }
        if (!email.matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$")) {
            JOptionPane.showMessageDialog(null, "E-mail inválido!");
            return false;
        }
        if (cpf.isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo 'CPF' está em branco.");
            return false;
        }
        if (!cpf.matches("^[0-9]{11}$") && !cpf.matches("^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$")) { 
            JOptionPane.showMessageDialog(null, "CPF inválido! Use o formato 000.000.000-00 ou apenas números.");
            return false;
        }

        if (txtTelefone.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo 'Telefone' está vazio.");
            return false;
        }
        if (!telefone.matches("^^[0-9]{11}$$")) {
            JOptionPane.showMessageDialog(null, "Telefone inválido! Use apenas números.");
            return false;
        }

        // Validação do Telefone
        if (telefone.isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo 'Telefone' está em branco.");
            return false;
        }
        if (!telefone.matches("^\\+?\\d{10,15}$")) {
            JOptionPane.showMessageDialog(this, "Telefone inválido! Use apenas números.");
            return false;
        }

        // Validação da Data de Nascimento
        if (dataNascimento.isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo 'Data de Nascimento' está em branco.");
            return false;
        }
        if (!dataNascimento.matches("^\\d{2}/\\d{2}/\\d{4}$")) {
            JOptionPane.showMessageDialog(null, "Data de nascimento inválida! Use o formato dd/mm/aaaa.");
            return false;
        }

        return true; // Se todos os campos forem válidos
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrAltCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrAltCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrAltCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrAltCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrAltCliente dialog = new FrAltCliente(new javax.swing.JFrame(), true, 1); // exemplo com id = 1

                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblDataNasc;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JFormattedTextField txtDataNasc;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
