/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.FinanceiroController;
import controller.ReservaController;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Financeiro;
import model.Reserva;

/**
 *
 * @author prisc
 */
public class FrConReserva extends javax.swing.JDialog {

    /**
     * Creates new form FrConAutores
     */
    public FrConReserva(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbtReservas = new javax.swing.JTable();
        btmExcluir = new javax.swing.JButton();
        btmVoltar = new javax.swing.JButton();
        btmPesquisar = new javax.swing.JButton();
        btmEditar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbtReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbtReservas);
        if (tbtReservas.getColumnModel().getColumnCount() > 0) {
            tbtReservas.getColumnModel().getColumn(0).setResizable(false);
            tbtReservas.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 290, 110));

        btmExcluir.setText("Excluir");
        btmExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btmExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        btmVoltar.setText("Voltar");
        btmVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btmVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        btmPesquisar.setText("Pesquisar");
        btmPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btmPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, -1));

        btmEditar1.setText("Editar");
        btmEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmEditar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btmEditar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmPesquisarActionPerformed
        carregarTabela();
    }//GEN-LAST:event_btmPesquisarActionPerformed

    private void btmVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btmVoltarActionPerformed

    private void btmExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmExcluirActionPerformed
        excluirReserva();
    }//GEN-LAST:event_btmExcluirActionPerformed

    private void btmEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmEditar1ActionPerformed
        editarReserva();
    }//GEN-LAST:event_btmEditar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrConReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrConReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrConReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrConReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrConReserva dialog = new FrConReserva(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void carregarTabela() {
        DefaultTableModel modelo = (DefaultTableModel) tbtReservas.getModel();
        modelo.setRowCount(0); 

        ReservaController controller = new ReservaController();
        List<Reserva> listaReservas = controller.consultar(); 

        for (Reserva reserva : listaReservas) {
            modelo.addRow(new Object[]{
                reserva.getId(),
                reserva.getClienteId(), 
                reserva.getPacoteId(), 
                reserva.getDataReserva(),
                reserva.getQuantidadePessoas(),
                reserva.getStatus()
            });
        }
    }

    private void excluirReserva() {
         int linhaSelecionada = tbtReservas.getSelectedRow();
    if (linhaSelecionada == -1) {
        JOptionPane.showMessageDialog(this, "Selecione uma reserva para excluir.", "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }

    int confirmacao = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir esta reserva?", "Confirmação", JOptionPane.YES_NO_OPTION);
    if (confirmacao == JOptionPane.YES_OPTION) {
        int id = (int) tbtReservas.getValueAt(linhaSelecionada, 0);
        ReservaController controller = new ReservaController();
        boolean sucesso = controller.excluir(id);  // Método para excluir no controller
        if (sucesso) {
            JOptionPane.showMessageDialog(this, "Reserva excluída com sucesso!");
            carregarTabela();
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao excluir reserva.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }
}

    private void editarReserva() {
        int linhaSelecionada = tbtReservas.getSelectedRow();
    if (linhaSelecionada == -1) {
        JOptionPane.showMessageDialog(this, "Selecione uma reserva para editar.", "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }

    int id = (int) tbtReservas.getValueAt(linhaSelecionada, 0);
    Date dataReservaAtual = (Date) tbtReservas.getValueAt(linhaSelecionada, 3);
    String statusAtual = (String) tbtReservas.getValueAt(linhaSelecionada, 5);

    String novoStatus = JOptionPane.showInputDialog(this, "Editar status da reserva:", statusAtual);

    if (novoStatus != null && !novoStatus.trim().isEmpty()) {
        Reserva reserva = new Reserva();
        reserva.setId(id);
        reserva.setStatus(novoStatus);
        reserva.setDataReserva(dataReservaAtual);
        ReservaController controller = new ReservaController();
        boolean sucesso = controller.atualizar(reserva); 
        if (sucesso) {
            JOptionPane.showMessageDialog(this, "Reserva atualizada com sucesso!");
            carregarTabela();
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao atualizar reserva.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    } else if (novoStatus != null) {
        JOptionPane.showMessageDialog(this, "O status não pode estar vazio.", "Aviso", JOptionPane.WARNING_MESSAGE);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmEditar1;
    private javax.swing.JButton btmExcluir;
    private javax.swing.JButton btmPesquisar;
    private javax.swing.JButton btmVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbtReservas;
    // End of variables declaration//GEN-END:variables
}
