/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author prisc
 */
public class FrDashboard extends javax.swing.JFrame {

    /**
     * Creates new form FrMenu
     */
    public FrDashboard() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        barMenu = new javax.swing.JMenuBar();
        meCadastro = new javax.swing.JMenu();
        miAltCadCliente = new javax.swing.JMenuItem();
        miCadDestino = new javax.swing.JMenuItem();
        miCadGuia = new javax.swing.JMenuItem();
        miCadPacote = new javax.swing.JMenuItem();
        miCadReserva = new javax.swing.JMenuItem();
        meVendas = new javax.swing.JMenu();
        miNaoSei = new javax.swing.JMenuItem();
        miSePrecisar = new javax.swing.JMenuItem();
        meSobre1 = new javax.swing.JMenu();
        miConCliente = new javax.swing.JMenuItem();
        miConGuias = new javax.swing.JMenuItem();
        miConDestinos = new javax.swing.JMenuItem();
        miConPacotes = new javax.swing.JMenuItem();
        miConReservas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 320));

        meCadastro.setText("Cadastro");

        miAltCadCliente.setText("Cliente");
        miAltCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAltCadClienteActionPerformed(evt);
            }
        });
        meCadastro.add(miAltCadCliente);

        miCadDestino.setText("Destino");
        miCadDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadDestinoActionPerformed(evt);
            }
        });
        meCadastro.add(miCadDestino);

        miCadGuia.setText("Guia");
        miCadGuia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadGuiaActionPerformed(evt);
            }
        });
        meCadastro.add(miCadGuia);

        miCadPacote.setText("Pacote");
        miCadPacote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadPacoteActionPerformed(evt);
            }
        });
        meCadastro.add(miCadPacote);

        miCadReserva.setText("Reserva");
        miCadReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadReservaActionPerformed(evt);
            }
        });
        meCadastro.add(miCadReserva);

        barMenu.add(meCadastro);

        meVendas.setText("alguma coisa");

        miNaoSei.setText(" nao sei");
        miNaoSei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNaoSeiActionPerformed(evt);
            }
        });
        meVendas.add(miNaoSei);

        miSePrecisar.setText("nao sei");
        miSePrecisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSePrecisarActionPerformed(evt);
            }
        });
        meVendas.add(miSePrecisar);

        barMenu.add(meVendas);

        meSobre1.setText("Consultar");

        miConCliente.setText("Clientes");
        miConCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConClienteActionPerformed(evt);
            }
        });
        meSobre1.add(miConCliente);

        miConGuias.setText("Guias");
        miConGuias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConGuiasActionPerformed(evt);
            }
        });
        meSobre1.add(miConGuias);

        miConDestinos.setText("Destinos");
        miConDestinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConDestinosActionPerformed(evt);
            }
        });
        meSobre1.add(miConDestinos);

        miConPacotes.setText("Pacotes");
        miConPacotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConPacotesActionPerformed(evt);
            }
        });
        meSobre1.add(miConPacotes);

        miConReservas.setText("Reservas");
        miConReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConReservasActionPerformed(evt);
            }
        });
        meSobre1.add(miConReservas);

        barMenu.add(meSobre1);

        setJMenuBar(barMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void miAltCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAltCadClienteActionPerformed
       FrCadCliente tela = new FrCadCliente(this, rootPaneCheckingEnabled);
    tela.setVisible(true);
    }//GEN-LAST:event_miAltCadClienteActionPerformed

    private void miCadDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadDestinoActionPerformed
       FrCadDestino tela = new FrCadDestino(this, rootPaneCheckingEnabled);
    tela.setVisible(true);
    }//GEN-LAST:event_miCadDestinoActionPerformed

    private void miCadGuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadGuiaActionPerformed
         FrCadGuia tela = new FrCadGuia(this, rootPaneCheckingEnabled);
    tela.setVisible(true);
    }//GEN-LAST:event_miCadGuiaActionPerformed

    private void miNaoSeiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNaoSeiActionPerformed
        FrCadReserva telaVenda = new FrCadReserva(this, rootPaneCheckingEnabled);

        telaVenda.setVisible(true);
    }//GEN-LAST:event_miNaoSeiActionPerformed

    private void miSePrecisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSePrecisarActionPerformed
      
    }//GEN-LAST:event_miSePrecisarActionPerformed

    private void miCadPacoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadPacoteActionPerformed
    FrConClienteIds tela = new FrConClienteIds(this, rootPaneCheckingEnabled);
    tela.setVisible(true);;
    }//GEN-LAST:event_miCadPacoteActionPerformed

    private void miConClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConClienteActionPerformed
      FrConCliente tela = new FrConCliente(this, rootPaneCheckingEnabled);
    tela.setVisible(true);
    }//GEN-LAST:event_miConClienteActionPerformed

    private void miConGuiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConGuiasActionPerformed
         FrConGuia tela = new FrConGuia(this, rootPaneCheckingEnabled);
    tela.setVisible(true);
    }//GEN-LAST:event_miConGuiasActionPerformed

    private void miConDestinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConDestinosActionPerformed
       FrConDestino tela = new FrConDestino(this, rootPaneCheckingEnabled);
    tela.setVisible(true);
    }//GEN-LAST:event_miConDestinosActionPerformed

    private void miConPacotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConPacotesActionPerformed
       FrConPacote tela = new FrConPacote(this, rootPaneCheckingEnabled);
    tela.setVisible(true);
    }//GEN-LAST:event_miConPacotesActionPerformed

    private void miConReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConReservasActionPerformed
         FrConReserva tela = new FrConReserva(this, rootPaneCheckingEnabled);
    tela.setVisible(true);
    }//GEN-LAST:event_miConReservasActionPerformed

    private void miCadReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadReservaActionPerformed
  FrCadReserva tela = new FrCadReserva(this, rootPaneCheckingEnabled);
    tela.setVisible(true);
    }//GEN-LAST:event_miCadReservaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu meCadastro;
    private javax.swing.JMenu meSobre1;
    private javax.swing.JMenu meVendas;
    private javax.swing.JMenuItem miAltCadCliente;
    private javax.swing.JMenuItem miCadDestino;
    private javax.swing.JMenuItem miCadGuia;
    private javax.swing.JMenuItem miCadPacote;
    private javax.swing.JMenuItem miCadReserva;
    private javax.swing.JMenuItem miConCliente;
    private javax.swing.JMenuItem miConDestinos;
    private javax.swing.JMenuItem miConGuias;
    private javax.swing.JMenuItem miConPacotes;
    private javax.swing.JMenuItem miConReservas;
    private javax.swing.JMenuItem miNaoSei;
    private javax.swing.JMenuItem miSePrecisar;
    // End of variables declaration//GEN-END:variables
}
